/* =====================================================================
   N4 道場 — Content pack (window.N4_CONTENT)  ·  N5 + N4 combined
   Built for a DIRECT-N4 candidate (no separate N5 prep): the full N5 sets are
   included as the real first layer, then N4 on top. Every item is tagged
   "level":"N5" or "N4". Ordered SIMPLE -> ADVANCED:
     • Kanji (245: 79 N5 + 166 N4) — by grade, frequency, strokes.
     • Grammar (120: 40 N5 + 80 N4) — foundational N5 first, advanced N4 last.
   Kanji readings/meanings: davidluzgouveia/kanji-data. Example words drawn from
   the vocab set. Full vocab lives in n4-vocab.js and supersedes the core below.
   ===================================================================== */
window.N4_CONTENT = {
kanji:[
  {"char": "日", "meaning": "day; sun", "on": "ニチ", "kun": "ひ", "ex": "日", "exr": "ひ", "exm": "day; days", "level": "N5"},
  {"char": "一", "meaning": "one; one radical (no.1)", "on": "イチ", "kun": "ひと-", "ex": "一", "exr": "いち", "exm": "one; 1", "level": "N5"},
  {"char": "人", "meaning": "person", "on": "ジン", "kun": "ひと", "ex": "人", "exr": "ひと", "exm": "person; someone; somebody", "level": "N5"},
  {"char": "年", "meaning": "year; counter for years", "on": "ネン", "kun": "とし", "ex": "年", "exr": "とし", "exm": "year", "level": "N5"},
  {"char": "大", "meaning": "large; big", "on": "ダイ", "kun": "おお-", "ex": "大人", "exr": "おとな", "exm": "adult; grown-up", "level": "N5"},
  {"char": "十", "meaning": "ten", "on": "ジュウ", "kun": "とお", "ex": "十", "exr": "じゅう とお", "exm": "ten; 10", "level": "N5"},
  {"char": "二", "meaning": "two; two radical (no. 7)", "on": "ニ", "kun": "ふた", "ex": "二", "exr": "に", "exm": "two; 2", "level": "N5"},
  {"char": "本", "meaning": "book; present", "on": "ホン", "kun": "もと", "ex": "本", "exr": "ほん", "exm": "book; volume; script", "level": "N5"},
  {"char": "中", "meaning": "in; inside", "on": "チュウ", "kun": "なか", "ex": "中", "exr": "なか", "exm": "inside; interior", "level": "N5"},
  {"char": "出", "meaning": "exit; leave", "on": "シュツ", "kun": "で(る)", "ex": "出す", "exr": "だす", "exm": "to take out; to get out", "level": "N5"},
  {"char": "三", "meaning": "three", "on": "サン", "kun": "み", "ex": "三", "exr": "さん", "exm": "three; 3", "level": "N5"},
  {"char": "見", "meaning": "see; hopes", "on": "ケン", "kun": "み(る)", "ex": "見せる", "exr": "みせる", "exm": "to show; to display", "level": "N5"},
  {"char": "月", "meaning": "month; moon", "on": "ゲツ", "kun": "つき", "ex": "一月", "exr": "ひとつき", "exm": "one month", "level": "N5"},
  {"char": "生", "meaning": "life; genuine", "on": "セイ", "kun": "い(きる)", "ex": "生きる", "exr": "いきる", "exm": "to live; to exist", "level": "N5"},
  {"char": "五", "meaning": "five", "on": "ゴ", "kun": "いつ", "ex": "五", "exr": "ご", "exm": "five; 5", "level": "N5"},
  {"char": "上", "meaning": "above; up", "on": "ジョウ", "kun": "うえ", "ex": "上", "exr": "うえ", "exm": "above; over; up", "level": "N5"},
  {"char": "四", "meaning": "four", "on": "シ", "kun": "よ", "ex": "四", "exr": "し", "exm": "four; 4", "level": "N5"},
  {"char": "金", "meaning": "gold", "on": "キン", "kun": "かね", "ex": "お金", "exr": "おかね", "exm": "money; 1. money", "level": "N5"},
  {"char": "九", "meaning": "nine", "on": "キュウ", "kun": "ここの", "ex": "九", "exr": "きゅう", "exm": "nine; 9", "level": "N5"},
  {"char": "入", "meaning": "enter; insert", "on": "ニュウ", "kun": "い(る)", "ex": "入る", "exr": "はいる", "exm": "to enter; to come in; to go in", "level": "N5"},
  {"char": "立", "meaning": "stand up; rise", "on": "リツ", "kun": "た(つ)", "ex": "立つ", "exr": "たつ", "exm": "to stand (up); to rise; to get to one's feet", "level": "N4"},
  {"char": "手", "meaning": "hand", "on": "シュ", "kun": "て", "ex": "手", "exr": "て", "exm": "hand; arm", "level": "N4"},
  {"char": "力", "meaning": "power; strength", "on": "リョク", "kun": "ちから", "ex": "力", "exr": "ちから", "exm": "force; strength; might", "level": "N4"},
  {"char": "学", "meaning": "study; learning", "on": "ガク", "kun": "まな(ぶ)", "ex": "学生", "exr": "がくせい", "exm": "student (esp. a university student)", "level": "N5"},
  {"char": "円", "meaning": "circle; yen", "on": "エン", "kun": "まる(い)", "ex": "円い", "exr": "まるい", "exm": "Marui", "level": "N5"},
  {"char": "子", "meaning": "child; sign of the rat", "on": "シ", "kun": "こ", "ex": "子", "exr": "こ", "exm": "child; kid; teenager", "level": "N5"},
  {"char": "目", "meaning": "eye; class", "on": "モク", "kun": "め", "ex": "目", "exr": "め", "exm": "eye; eyeball", "level": "N4"},
  {"char": "田", "meaning": "rice field; rice paddy", "on": "デン", "kun": "た", "ex": "田舎", "exr": "いなか", "exm": "rural area; countryside; the sticks", "level": "N4"},
  {"char": "八", "meaning": "eight; eight radical (no. 12)", "on": "ハチ", "kun": "や", "ex": "八", "exr": "はち", "exm": "eight; 8", "level": "N5"},
  {"char": "六", "meaning": "six", "on": "ロク", "kun": "む", "ex": "六", "exr": "ろく", "exm": "six; 6", "level": "N5"},
  {"char": "下", "meaning": "below; down", "on": "カ", "kun": "した", "ex": "下", "exr": "した", "exm": "below; down; under", "level": "N5"},
  {"char": "気", "meaning": "spirit; mind", "on": "キ", "kun": "いき", "ex": "気", "exr": "き", "exm": "spirit; mind; heart", "level": "N5"},
  {"char": "小", "meaning": "little; small", "on": "ショウ", "kun": "ちい(さい)", "ex": "小さい", "exr": "ちいさい", "exm": "small; little; tiny", "level": "N5"},
  {"char": "七", "meaning": "seven", "on": "シチ", "kun": "なな", "ex": "七", "exr": "しち", "exm": "seven", "level": "N5"},
  {"char": "山", "meaning": "mountain", "on": "サン", "kun": "やま", "ex": "山", "exr": "やま", "exm": "mountain; hill", "level": "N5"},
  {"char": "正", "meaning": "correct; justice", "on": "セイ", "kun": "ただ(しい)", "ex": "正しい", "exr": "ただしい", "exm": "right; correct", "level": "N4"},
  {"char": "女", "meaning": "woman; female", "on": "ジョ", "kun": "おんな", "ex": "女", "exr": "おんな", "exm": "woman; female", "level": "N5"},
  {"char": "百", "meaning": "hundred", "on": "ヒャク", "kun": "もも", "ex": "百", "exr": "ひゃく", "exm": "hundred; 100", "level": "N5"},
  {"char": "先", "meaning": "before; ahead", "on": "セン", "kun": "さき", "ex": "先", "exr": "さき", "exm": "point; tip; end", "level": "N5"},
  {"char": "名", "meaning": "name; noted", "on": "メイ", "kun": "な", "ex": "名前", "exr": "なまえ", "exm": "name", "level": "N5"},
  {"char": "川", "meaning": "stream; river", "on": "セン", "kun": "かわ", "ex": "川", "exr": "かわ", "exm": "river; stream", "level": "N5"},
  {"char": "文", "meaning": "sentence; literature", "on": "ブン", "kun": "ふみ", "ex": "文学", "exr": "ぶんがく", "exm": "literature", "level": "N4"},
  {"char": "千", "meaning": "thousand", "on": "セン", "kun": "ち", "ex": "千", "exr": "せん", "exm": "thousand; 1,000", "level": "N5"},
  {"char": "水", "meaning": "water", "on": "スイ", "kun": "みず", "ex": "水", "exr": "みず", "exm": "water (esp. cool or cold); 1. hot water", "level": "N5"},
  {"char": "男", "meaning": "male", "on": "ダン", "kun": "おとこ", "ex": "男", "exr": "おとこ", "exm": "man; male; 1. woman; female", "level": "N5"},
  {"char": "口", "meaning": "mouth", "on": "コウ", "kun": "くち", "ex": "口", "exr": "くち", "exm": "mouth", "level": "N4"},
  {"char": "町", "meaning": "town; village", "on": "チョウ", "kun": "まち", "ex": "町", "exr": "まち", "exm": "town; block; neighbourhood", "level": "N4"},
  {"char": "校", "meaning": "exam; school", "on": "コウ", "kun": "—", "ex": "学校", "exr": "がっこう", "exm": "school", "level": "N5"},
  {"char": "空", "meaning": "empty; sky", "on": "クウ", "kun": "そら", "ex": "空", "exr": "そら", "exm": "sky; the air; the heavens", "level": "N4"},
  {"char": "土", "meaning": "soil; earth", "on": "ド", "kun": "つち", "ex": "土曜日", "exr": "どようび", "exm": "Saturday", "level": "N5"},
  {"char": "木", "meaning": "tree; wood", "on": "ボク", "kun": "き", "ex": "木", "exr": "き", "exm": "tree; shrub; bush", "level": "N5"},
  {"char": "車", "meaning": "car", "on": "シャ", "kun": "くるま", "ex": "車", "exr": "くるま", "exm": "car; automobile; vehicle", "level": "N5"},
  {"char": "足", "meaning": "leg; foot", "on": "ソク", "kun": "あし", "ex": "足", "exr": "あし", "exm": "foot; paw; arm (of an octopus, squid, etc.)", "level": "N4"},
  {"char": "早", "meaning": "early; fast", "on": "ソウ", "kun": "はや(い)", "ex": "早い", "exr": "はやい", "exm": "fast; quick; rapid", "level": "N4"},
  {"char": "白", "meaning": "white", "on": "ハク", "kun": "しろ", "ex": "白", "exr": "しろ", "exm": "white", "level": "N5"},
  {"char": "字", "meaning": "character; letter", "on": "ジ", "kun": "あざ", "ex": "字", "exr": "じ", "exm": "character (esp. kanji); letter; written text", "level": "N4"},
  {"char": "音", "meaning": "sound; noise", "on": "オン", "kun": "おと", "ex": "音", "exr": "おと", "exm": "sound; noise", "level": "N4"},
  {"char": "天", "meaning": "heavens; sky", "on": "テン", "kun": "あまつ", "ex": "天気", "exr": "てんき", "exm": "weather", "level": "N5"},
  {"char": "火", "meaning": "fire", "on": "カ", "kun": "ひ", "ex": "火", "exr": "ひ", "exm": "fire; flame; blaze", "level": "N5"},
  {"char": "花", "meaning": "flower", "on": "カ", "kun": "はな", "ex": "花", "exr": "はな", "exm": "flower; blossom; bloom", "level": "N4"},
  {"char": "赤", "meaning": "red", "on": "セキ", "kun": "あか", "ex": "赤", "exr": "あか", "exm": "red; crimson; scarlet", "level": "N4"},
  {"char": "青", "meaning": "blue; green", "on": "セイ", "kun": "あお", "ex": "青", "exr": "あお", "exm": "blue; azure", "level": "N4"},
  {"char": "右", "meaning": "right", "on": "ウ", "kun": "みぎ", "ex": "右", "exr": "みぎ", "exm": "right; right-hand side", "level": "N5"},
  {"char": "左", "meaning": "left", "on": "サ", "kun": "ひだり", "ex": "左", "exr": "ひだり", "exm": "left; left-hand side", "level": "N5"},
  {"char": "休", "meaning": "rest; day off", "on": "キュウ", "kun": "やす(む)", "ex": "休み", "exr": "やすみ", "exm": "rest; recess; respite", "level": "N5"},
  {"char": "夕", "meaning": "evening", "on": "セキ", "kun": "ゆう", "ex": "夕方", "exr": "ゆうがた", "exm": "early evening (usu. from 3pm to 6pm); dusk", "level": "N4"},
  {"char": "雨", "meaning": "rain", "on": "ウ", "kun": "あめ", "ex": "雨", "exr": "あめ", "exm": "rain", "level": "N5"},
  {"char": "犬", "meaning": "dog", "on": "ケン", "kun": "いぬ", "ex": "犬", "exr": "いぬ", "exm": "dog (Canis (lupus) familiaris)", "level": "N4"},
  {"char": "国", "meaning": "country", "on": "コク", "kun": "くに", "ex": "国", "exr": "くに", "exm": "country; state", "level": "N5"},
  {"char": "会", "meaning": "meeting; meet", "on": "カイ", "kun": "あ(う)", "ex": "会う", "exr": "あう", "exm": "to meet; to encounter; to see", "level": "N4"},
  {"char": "長", "meaning": "long; leader", "on": "チョウ", "kun": "なが(い)", "ex": "長い", "exr": "ながい", "exm": "long (distance, length); antonym:", "level": "N5"},
  {"char": "同", "meaning": "same; agree", "on": "ドウ", "kun": "おな(じ)", "ex": "同じ", "exr": "おなじ", "exm": "same; identical; equal", "level": "N4"},
  {"char": "時", "meaning": "time; hour", "on": "ジ", "kun": "とき", "ex": "時々", "exr": "ときどき", "exm": "sometimes; occasionally; at times", "level": "N5"},
  {"char": "自", "meaning": "oneself", "on": "ジ", "kun": "みずか(ら)", "ex": "自分", "exr": "じぶん", "exm": "myself; yourself; oneself", "level": "N4"},
  {"char": "行", "meaning": "going; journey", "on": "コウ", "kun": "い(く)", "ex": "行く", "exr": "いく", "exm": "to go; to move (towards); to head (towards)", "level": "N5"},
  {"char": "社", "meaning": "company; firm", "on": "シャ", "kun": "やしろ", "ex": "会社", "exr": "かいしゃ", "exm": "company; corporation; firm", "level": "N4"},
  {"char": "後", "meaning": "behind; back", "on": "ゴ", "kun": "のち", "ex": "後", "exr": "あと", "exm": "behind; rear", "level": "N5"},
  {"char": "前", "meaning": "in front; before", "on": "ゼン", "kun": "まえ", "ex": "前", "exr": "まえ", "exm": "in front (of); before (e.g. a building)", "level": "N5"},
  {"char": "間", "meaning": "interval; space", "on": "カン", "kun": "あいだ", "ex": "間", "exr": "あいだ", "exm": "space (between); gap; interval", "level": "N5"},
  {"char": "東", "meaning": "east", "on": "トウ", "kun": "ひがし", "ex": "東", "exr": "ひがし", "exm": "east", "level": "N5"},
  {"char": "地", "meaning": "ground; earth", "on": "チ", "kun": "—", "ex": "地理", "exr": "ちり", "exm": "geography", "level": "N4"},
  {"char": "方", "meaning": "direction; person", "on": "ホウ", "kun": "かた", "ex": "方", "exr": "かた", "exm": "direction; way", "level": "N4"},
  {"char": "今", "meaning": "now", "on": "コン", "kun": "いま", "ex": "今", "exr": "いま", "exm": "now; the present time; just now", "level": "N5"},
  {"char": "新", "meaning": "new", "on": "シン", "kun": "あたら(しい)", "ex": "新しい", "exr": "あたらしい", "exm": "new; novel; fresh", "level": "N4"},
  {"char": "場", "meaning": "location; place", "on": "ジョウ", "kun": "ば", "ex": "会場", "exr": "かいじょう", "exm": "assembly hall; meeting place; venue", "level": "N4"},
  {"char": "高", "meaning": "tall; high", "on": "コウ", "kun": "たか(い)", "ex": "高い", "exr": "たかい", "exm": "high; tall; antonym:", "level": "N5"},
  {"char": "明", "meaning": "bright; light", "on": "メイ", "kun": "あ(かり)", "ex": "明い", "exr": "あかるい", "exm": "light; bright; well-lit", "level": "N4"},
  {"char": "京", "meaning": "capital; 10**16", "on": "キョウ", "kun": "みやこ", "ex": "京", "exr": "みやこ", "exm": "Capital; 10**16", "level": "N4"},
  {"char": "通", "meaning": "traffic; pass through", "on": "ツウ", "kun": "とお(る)", "ex": "通う", "exr": "かよう", "exm": "to go to and from (a place); to go back and forth between; to run between (e.g. bus, train, etc.)", "level": "N4"},
  {"char": "外", "meaning": "outside", "on": "ガイ", "kun": "そと", "ex": "外", "exr": "そと", "exm": "outside; exterior", "level": "N5"},
  {"char": "言", "meaning": "say; word", "on": "ゲン", "kun": "い(う)", "ex": "言う", "exr": "いう", "exm": "to say; to utter; to declare", "level": "N4"},
  {"char": "理", "meaning": "logic; arrangement", "on": "リ", "kun": "ことわり", "ex": "地理", "exr": "ちり", "exm": "geography", "level": "N4"},
  {"char": "体", "meaning": "body; substance", "on": "タイ", "kun": "からだ", "ex": "体", "exr": "からだ", "exm": "body", "level": "N4"},
  {"char": "来", "meaning": "come; due", "on": "ライ", "kun": "く(る)", "ex": "来る", "exr": "くる", "exm": "to come (spatially or temporally); to approach; to arrive", "level": "N5"},
  {"char": "作", "meaning": "make; production", "on": "サク", "kun": "つく(る)", "ex": "作文", "exr": "さくぶん", "exm": "writing (an essay, prose, etc.); composition; writing (poetry); composing", "level": "N4"},
  {"char": "用", "meaning": "utilize; business", "on": "ヨウ", "kun": "もち(いる)", "ex": "用", "exr": "よう", "exm": "business; task; errand", "level": "N4"},
  {"char": "強", "meaning": "strong", "on": "キョウ", "kun": "つよ(い)", "ex": "強い", "exr": "つよい", "exm": "strong; potent; competent", "level": "N4"},
  {"char": "公", "meaning": "public; prince", "on": "コウ", "kun": "おおやけ", "ex": "公園", "exr": "こうえん", "exm": "(public) park", "level": "N4"},
  {"char": "野", "meaning": "plains; field", "on": "ヤ", "kun": "の", "ex": "野菜", "exr": "やさい", "exm": "vegetable", "level": "N4"},
  {"char": "思", "meaning": "think", "on": "シ", "kun": "おも(う)", "ex": "思う", "exr": "おもう", "exm": "to think; to consider; to believe", "level": "N4"},
  {"char": "家", "meaning": "house; home", "on": "カ", "kun": "いえ", "ex": "家", "exr": "いえ", "exm": "house; residence; dwelling", "level": "N4"},
  {"char": "話", "meaning": "tale; talk", "on": "ワ", "kun": "はな(す)", "ex": "話", "exr": "はなし", "exm": "talk; speech; chat", "level": "N5"},
  {"char": "多", "meaning": "many; frequent", "on": "タ", "kun": "おお(い)", "ex": "多い", "exr": "おおい", "exm": "many; numerous; a lot", "level": "N4"},
  {"char": "北", "meaning": "north", "on": "ホク", "kun": "きた", "ex": "北", "exr": "きた", "exm": "north", "level": "N5"},
  {"char": "午", "meaning": "noon; sign of the horse", "on": "ゴ", "kun": "うま", "ex": "午後", "exr": "ごご", "exm": "afternoon; p.m.", "level": "N5"},
  {"char": "心", "meaning": "heart; mind", "on": "シン", "kun": "こころ", "ex": "心", "exr": "こころ", "exm": "mind; heart; spirit", "level": "N4"},
  {"char": "教", "meaning": "teach; faith", "on": "キョウ", "kun": "おし(える)", "ex": "教会", "exr": "きょうかい", "exm": "church; congregation", "level": "N4"},
  {"char": "書", "meaning": "write", "on": "ショ", "kun": "か(く)", "ex": "書く", "exr": "かく", "exm": "to write; to compose; to pen", "level": "N5"},
  {"char": "元", "meaning": "beginning; former time", "on": "ゲン", "kun": "もと", "ex": "元気", "exr": "げんき", "exm": "lively; full of spirit; energetic", "level": "N4"},
  {"char": "近", "meaning": "near; early", "on": "キン", "kun": "ちか(い)", "ex": "近い", "exr": "ちかい", "exm": "near; close; short (distance)", "level": "N4"},
  {"char": "考", "meaning": "consider; think over", "on": "コウ", "kun": "かんが(える)", "ex": "考える", "exr": "かんがえる", "exm": "to think (about, of); to think over; to ponder", "level": "N4"},
  {"char": "画", "meaning": "brush-stroke; picture", "on": "ガ", "kun": "えが(く)", "ex": "計画", "exr": "けいかく", "exm": "plan; project; schedule", "level": "N4"},
  {"char": "海", "meaning": "sea; ocean", "on": "カイ", "kun": "うみ", "ex": "海", "exr": "うみ", "exm": "sea; ocean; waters", "level": "N4"},
  {"char": "売", "meaning": "sell", "on": "バイ", "kun": "う(る)", "ex": "売る", "exr": "うる", "exm": "to sell", "level": "N4"},
  {"char": "知", "meaning": "know; wisdom", "on": "チ", "kun": "し(る)", "ex": "知る", "exr": "しる", "exm": "to know; to be aware (of); to be conscious (of)", "level": "N4"},
  {"char": "道", "meaning": "road-way; street", "on": "ドウ", "kun": "みち", "ex": "道", "exr": "みち", "exm": "road; path; street", "level": "N4"},
  {"char": "半", "meaning": "half; middle", "on": "ハン", "kun": "なか(ば)", "ex": "半", "exr": "はん", "exm": "half; semi-; partial", "level": "N5"},
  {"char": "計", "meaning": "plot; plan", "on": "ケイ", "kun": "はか(る)", "ex": "時計", "exr": "とけい", "exm": "clock; watch; timepiece", "level": "N4"},
  {"char": "朝", "meaning": "morning; dynasty", "on": "チョウ", "kun": "あさ", "ex": "朝", "exr": "あさ", "exm": "morning", "level": "N4"},
  {"char": "西", "meaning": "west; spain", "on": "セイ", "kun": "にし", "ex": "西", "exr": "にし", "exm": "west", "level": "N5"},
  {"char": "台", "meaning": "pedestal; a stand", "on": "ダイ", "kun": "うてな", "ex": "台風", "exr": "たいふう", "exm": "typhoon; hurricane", "level": "N4"},
  {"char": "広", "meaning": "wide; broad", "on": "コウ", "kun": "ひろ(い)", "ex": "広い", "exr": "ひろい", "exm": "spacious; vast; wide", "level": "N4"},
  {"char": "電", "meaning": "electricity", "on": "デン", "kun": "—", "ex": "電気", "exr": "でんき", "exm": "electricity", "level": "N5"},
  {"char": "少", "meaning": "few; little", "on": "ショウ", "kun": "すく(ない)", "ex": "少し", "exr": "すこし", "exm": "a little; a bit; a small amount", "level": "N4"},
  {"char": "工", "meaning": "craft; construction", "on": "コウ", "kun": "—", "ex": "工場", "exr": "こうじょう", "exm": "factory; plant; mill", "level": "N4"},
  {"char": "語", "meaning": "word; speech", "on": "ゴ", "kun": "かた(る)", "ex": "英語", "exr": "えいご", "exm": "English (language)", "level": "N5"},
  {"char": "止", "meaning": "stop; halt", "on": "シ", "kun": "と(まる)", "ex": "止む", "exr": "やむ", "exm": "to cease; to stop; to be over", "level": "N4"},
  {"char": "聞", "meaning": "hear; ask", "on": "ブン", "kun": "き(く)", "ex": "聞く", "exr": "きく", "exm": "to hear", "level": "N5"},
  {"char": "切", "meaning": "cut; cutoff", "on": "セツ", "kun": "き(る)", "ex": "切手", "exr": "きって", "exm": "stamp (postage)", "level": "N4"},
  {"char": "食", "meaning": "eat; food", "on": "ショク", "kun": "く(う)", "ex": "食べる", "exr": "たべる", "exm": "to eat", "level": "N5"},
  {"char": "何", "meaning": "what", "on": "カ", "kun": "なに", "ex": "何", "exr": "なん", "exm": "what", "level": "N5"},
  {"char": "南", "meaning": "south", "on": "ナン", "kun": "みなみ", "ex": "南", "exr": "みなみ", "exm": "south", "level": "N5"},
  {"char": "楽", "meaning": "music; comfort", "on": "ガク", "kun": "たの(しい)", "ex": "音楽", "exr": "おんがく", "exm": "music", "level": "N4"},
  {"char": "万", "meaning": "ten thousand; 10,000", "on": "マン", "kun": "よろず", "ex": "万", "exr": "まん", "exm": "10,000; ten thousand", "level": "N5"},
  {"char": "店", "meaning": "store; shop", "on": "テン", "kun": "みせ", "ex": "店", "exr": "みせ", "exm": "store; shop; establishment", "level": "N4"},
  {"char": "親", "meaning": "parent; intimacy", "on": "シン", "kun": "おや", "ex": "親", "exr": "おや", "exm": "parent; parents; mother and father", "level": "N4"},
  {"char": "毎", "meaning": "every", "on": "マイ", "kun": "ごと", "ex": "毎朝", "exr": "まいあさ", "exm": "every morning", "level": "N5"},
  {"char": "答", "meaning": "solution; answer", "on": "トウ", "kun": "こた(える)", "ex": "答", "exr": "こたえ", "exm": "answer; reply; response", "level": "N4"},
  {"char": "夜", "meaning": "night; evening", "on": "ヤ", "kun": "よ", "ex": "夜", "exr": "よる", "exm": "night; evening", "level": "N4"},
  {"char": "帰", "meaning": "homecoming; arrive at", "on": "キ", "kun": "かえ(る)", "ex": "帰る", "exr": "かえる", "exm": "to return; to come home; to go home", "level": "N4"},
  {"char": "古", "meaning": "old", "on": "コ", "kun": "ふる(い)", "ex": "古い", "exr": "ふるい", "exm": "old; aged; ancient", "level": "N4"},
  {"char": "歌", "meaning": "song; sing", "on": "カ", "kun": "うた", "ex": "歌", "exr": "うた", "exm": "song; singing", "level": "N4"},
  {"char": "買", "meaning": "buy", "on": "バイ", "kun": "か(う)", "ex": "買う", "exr": "かう", "exm": "to buy; to purchase", "level": "N4"},
  {"char": "図", "meaning": "map; drawing", "on": "ズ", "kun": "え", "ex": "地図", "exr": "ちず", "exm": "map; atlas; chart", "level": "N4"},
  {"char": "週", "meaning": "week", "on": "シュウ", "kun": "—", "ex": "今週", "exr": "こんしゅう", "exm": "this week", "level": "N4"},
  {"char": "室", "meaning": "room; apartment", "on": "シツ", "kun": "むろ", "ex": "教室", "exr": "きょうしつ", "exm": "classroom; lecture room", "level": "N4"},
  {"char": "歩", "meaning": "walk; counter for steps", "on": "ホ", "kun": "ある(く)", "ex": "歩く", "exr": "あるく", "exm": "to walk", "level": "N4"},
  {"char": "風", "meaning": "wind; air", "on": "フウ", "kun": "かぜ", "ex": "風", "exr": "かぜ", "exm": "wind; breeze; draught", "level": "N4"},
  {"char": "紙", "meaning": "paper", "on": "シ", "kun": "かみ", "ex": "紙", "exr": "かみ", "exm": "paper", "level": "N4"},
  {"char": "母", "meaning": "mother", "on": "ボ", "kun": "はは", "ex": "お母さん", "exr": "おかあさん", "exm": "mother; mom; mum", "level": "N5"},
  {"char": "黒", "meaning": "black", "on": "コク", "kun": "くろ", "ex": "黒", "exr": "くろ", "exm": "black", "level": "N4"},
  {"char": "春", "meaning": "springtime; spring (season)", "on": "シュン", "kun": "はる", "ex": "春", "exr": "はる", "exm": "spring; springtime", "level": "N4"},
  {"char": "読", "meaning": "read", "on": "ドク", "kun": "よ(む)", "ex": "読む", "exr": "よむ", "exm": "to read", "level": "N5"},
  {"char": "色", "meaning": "color", "on": "ショク", "kun": "いろ", "ex": "色", "exr": "いろ", "exm": "colour; color; hue", "level": "N4"},
  {"char": "友", "meaning": "friend", "on": "ユウ", "kun": "とも", "ex": "友達", "exr": "ともだち", "exm": "friend; companion", "level": "N5"},
  {"char": "走", "meaning": "run", "on": "ソウ", "kun": "はし(る)", "ex": "走る", "exr": "はしる", "exm": "to run", "level": "N4"},
  {"char": "秋", "meaning": "autumn", "on": "シュウ", "kun": "あき", "ex": "秋", "exr": "あき", "exm": "autumn; fall", "level": "N4"},
  {"char": "父", "meaning": "father", "on": "フ", "kun": "ちち", "ex": "お父さん", "exr": "おとうさん", "exm": "father; dad; papa", "level": "N5"},
  {"char": "夏", "meaning": "summer", "on": "カ", "kun": "なつ", "ex": "夏", "exr": "なつ", "exm": "summer", "level": "N4"},
  {"char": "曜", "meaning": "weekday", "on": "ヨウ", "kun": "—", "ex": "火曜日", "exr": "かようび", "exm": "Tuesday", "level": "N4"},
  {"char": "肉", "meaning": "meat", "on": "ニク", "kun": "しし", "ex": "肉", "exr": "にく", "exm": "flesh", "level": "N4"},
  {"char": "鳥", "meaning": "bird; chicken", "on": "チョウ", "kun": "とり", "ex": "鳥", "exr": "とり", "exm": "bird", "level": "N4"},
  {"char": "冬", "meaning": "winter", "on": "トウ", "kun": "ふゆ", "ex": "冬", "exr": "ふゆ", "exm": "winter", "level": "N4"},
  {"char": "昼", "meaning": "daytime; noon", "on": "チュウ", "kun": "ひる", "ex": "昼", "exr": "ひる", "exm": "noon; midday", "level": "N4"},
  {"char": "茶", "meaning": "tea", "on": "チャ", "kun": "—", "ex": "お茶", "exr": "おちゃ", "exm": "tea (esp. green or barley)", "level": "N4"},
  {"char": "弟", "meaning": "younger brother; faithful service to elders", "on": "テイ", "kun": "おとうと", "ex": "弟", "exr": "おとうと", "exm": "younger brother; little brother; kid brother", "level": "N4"},
  {"char": "牛", "meaning": "cow", "on": "ギュウ", "kun": "うし", "ex": "牛肉", "exr": "ぎゅうにく", "exm": "beef", "level": "N4"},
  {"char": "魚", "meaning": "fish", "on": "ギョ", "kun": "うお", "ex": "魚", "exr": "さかな", "exm": "fish", "level": "N4"},
  {"char": "兄", "meaning": "elder brother; big brother", "on": "ケイ", "kun": "あに", "ex": "兄", "exr": "あに", "exm": "older brother; elder brother", "level": "N4"},
  {"char": "妹", "meaning": "younger sister", "on": "マイ", "kun": "いもうと", "ex": "妹", "exr": "いもうと", "exm": "younger sister", "level": "N4"},
  {"char": "姉", "meaning": "elder sister", "on": "シ", "kun": "あね", "ex": "姉", "exr": "あね", "exm": "older sister; elder sister", "level": "N4"},
  {"char": "事", "meaning": "matter; thing", "on": "ジ", "kun": "こと", "ex": "火事", "exr": "かじ", "exm": "fire; conflagration", "level": "N4"},
  {"char": "発", "meaning": "departure; discharge", "on": "ハツ", "kun": "た(つ)", "ex": "出発", "exr": "しゅっぱつ", "exm": "departure; leaving; setting off", "level": "N4"},
  {"char": "者", "meaning": "someone; person", "on": "シャ", "kun": "もの", "ex": "医者", "exr": "いしゃ", "exm": "doctor; physician", "level": "N4"},
  {"char": "業", "meaning": "business; vocation", "on": "ギョウ", "kun": "わざ", "ex": "工業", "exr": "こうぎょう", "exm": "(manufacturing) industry", "level": "N4"},
  {"char": "員", "meaning": "employee; member", "on": "イン", "kun": "—", "ex": "店員", "exr": "てんいん", "exm": "employee (of a store); shop assistant; clerk", "level": "N4"},
  {"char": "開", "meaning": "open; unfold", "on": "カイ", "kun": "ひら(く)", "ex": "開く", "exr": "あく", "exm": "to open (e.g. doors)", "level": "N4"},
  {"char": "問", "meaning": "question; ask", "on": "モン", "kun": "と(う)", "ex": "問題", "exr": "もんだい", "exm": "question (e.g. on a test); problem", "level": "N4"},
  {"char": "代", "meaning": "substitute; change", "on": "ダイ", "kun": "か(わる)", "ex": "時代", "exr": "じだい", "exm": "period; epoch; era", "level": "N4"},
  {"char": "動", "meaning": "move; motion", "on": "ドウ", "kun": "うご(く)", "ex": "動く", "exr": "うごく", "exm": "to move; to stir; to shift", "level": "N4"},
  {"char": "主", "meaning": "lord; chief", "on": "シュ", "kun": "ぬし", "ex": "御主人", "exr": "ごしゅじん", "exm": "your husband; her husband", "level": "N4"},
  {"char": "題", "meaning": "topic; subject", "on": "ダイ", "kun": "—", "ex": "問題", "exr": "もんだい", "exm": "question (e.g. on a test); problem", "level": "N4"},
  {"char": "意", "meaning": "idea; mind", "on": "イ", "kun": "—", "ex": "意見", "exr": "いけん", "exm": "opinion; view; comment", "level": "N4"},
  {"char": "度", "meaning": "degrees; occurrence", "on": "ド", "kun": "たび", "ex": "一度", "exr": "いちど", "exm": "once; one time; on one occasion", "level": "N4"},
  {"char": "持", "meaning": "hold; have", "on": "ジ", "kun": "も(つ)", "ex": "持つ", "exr": "もつ", "exm": "to hold (in one's hand); to take; to carry", "level": "N4"},
  {"char": "世", "meaning": "generation; world", "on": "セイ", "kun": "よ", "ex": "世話", "exr": "せわ", "exm": "care; looking after; help", "level": "N4"},
  {"char": "安", "meaning": "relax; cheap", "on": "アン", "kun": "やす(い)", "ex": "安い", "exr": "やすい", "exm": "cheap; inexpensive", "level": "N4"},
  {"char": "院", "meaning": "inst.; institution", "on": "イン", "kun": "—", "ex": "入院", "exr": "にゅういん", "exm": "hospitalization; hospitalisation", "level": "N4"},
  {"char": "界", "meaning": "world; boundary", "on": "カイ", "kun": "—", "ex": "世界", "exr": "せかい", "exm": "the world; society; the universe", "level": "N4"},
  {"char": "重", "meaning": "heavy; important", "on": "ジュウ", "kun": "え", "ex": "重い", "exr": "おもい", "exm": "heavy; weighty; antonym:", "level": "N4"},
  {"char": "集", "meaning": "gather; meet", "on": "シュウ", "kun": "あつ(まる)", "ex": "集る", "exr": "あつまる", "exm": "to gather; to crowd round; to swarm", "level": "N4"},
  {"char": "物", "meaning": "thing; object", "on": "ブツ", "kun": "もの", "ex": "物", "exr": "もの", "exm": "thing; object; article", "level": "N4"},
  {"char": "使", "meaning": "use; send on a mission", "on": "シ", "kun": "つか(う)", "ex": "使う", "exr": "つかう", "exm": "to use (a tool, method, etc.); to make use of; to put to use", "level": "N4"},
  {"char": "品", "meaning": "goods; refinement", "on": "ヒン", "kun": "しな", "ex": "品物", "exr": "しなもの", "exm": "article; item; thing", "level": "N4"},
  {"char": "死", "meaning": "death; die", "on": "シ", "kun": "し(ぬ)", "ex": "死ぬ", "exr": "しぬ", "exm": "to die; to pass away", "level": "N4"},
  {"char": "始", "meaning": "commence; begin", "on": "シ", "kun": "はじ(める)", "ex": "始め", "exr": "はじめ", "exm": "beginning; start; outset", "level": "N4"},
  {"char": "運", "meaning": "carry; luck", "on": "ウン", "kun": "はこ(ぶ)", "ex": "運動", "exr": "うんどう", "exm": "exercise; physical training; workout", "level": "N4"},
  {"char": "終", "meaning": "end; finish", "on": "シュウ", "kun": "お(わる)", "ex": "終る", "exr": "おわる", "exm": "to end; to come to an end; to finish", "level": "N4"},
  {"char": "住", "meaning": "dwell; reside", "on": "ジュウ", "kun": "す(む)", "ex": "住む", "exr": "すむ", "exm": "to live (of humans); to reside; to inhabit", "level": "N4"},
  {"char": "真", "meaning": "true; reality", "on": "シン", "kun": "ま", "ex": "真中", "exr": "まんなか", "exm": "middle; centre; center", "level": "N4"},
  {"char": "有", "meaning": "possess; have", "on": "ユウ", "kun": "あ(る)", "ex": "有名", "exr": "ゆうめい", "exm": "famous; well-known", "level": "N4"},
  {"char": "急", "meaning": "hurry; emergency", "on": "キュウ", "kun": "いそ(ぐ)", "ex": "急", "exr": "きゅう", "exm": "sudden; abrupt; unexpected", "level": "N4"},
  {"char": "送", "meaning": "escort; send", "on": "ソウ", "kun": "おく(る)", "ex": "送る", "exr": "おくる", "exm": "to send; to dispatch; to forward", "level": "N4"},
  {"char": "転", "meaning": "revolve; turn around", "on": "テン", "kun": "ころ(がる)", "ex": "運転", "exr": "うんてん", "exm": "operation (of a machine); running; working", "level": "N4"},
  {"char": "研", "meaning": "polish; study of", "on": "ケン", "kun": "と(ぐ)", "ex": "研究", "exr": "けんきゅう", "exm": "research; study; investigation", "level": "N4"},
  {"char": "究", "meaning": "research; study", "on": "キュウ", "kun": "きわ(める)", "ex": "研究", "exr": "けんきゅう", "exm": "research; study; investigation", "level": "N4"},
  {"char": "起", "meaning": "rouse; wake up", "on": "キ", "kun": "お(きる)", "ex": "起す", "exr": "おこす", "exm": "to build (a fire); to make; to start", "level": "N4"},
  {"char": "着", "meaning": "don; arrive", "on": "チャク", "kun": "き(る)", "ex": "上着", "exr": "うわぎ", "exm": "coat; jacket; outerwear", "level": "N4"},
  {"char": "病", "meaning": "ill; sick", "on": "ビョウ", "kun": "や(む)", "ex": "病院", "exr": "びょういん", "exm": "hospital; clinic; doctor's office", "level": "N4"},
  {"char": "待", "meaning": "wait; depend on", "on": "タイ", "kun": "ま(つ)", "ex": "待つ", "exr": "まつ", "exm": "to wait", "level": "N4"},
  {"char": "族", "meaning": "tribe; family", "on": "ゾク", "kun": "—", "ex": "家族", "exr": "かぞく", "exm": "family", "level": "N4"},
  {"char": "銀", "meaning": "silver", "on": "ギン", "kun": "しろがね", "ex": "銀行", "exr": "ぎんこう", "exm": "bank; banking institution", "level": "N4"},
  {"char": "医", "meaning": "doctor; medicine", "on": "イ", "kun": "い(やす)", "ex": "医者", "exr": "いしゃ", "exm": "doctor; physician", "level": "N4"},
  {"char": "仕", "meaning": "attend; doing", "on": "シ", "kun": "つか(える)", "ex": "仕事", "exr": "しごと", "exm": "work; job; labor", "level": "N4"},
  {"char": "去", "meaning": "gone; past", "on": "キョ", "kun": "さ(る)", "ex": "去年", "exr": "きょねん", "exm": "last year", "level": "N4"},
  {"char": "味", "meaning": "flavor; taste", "on": "ミ", "kun": "あじ", "ex": "味", "exr": "あじ", "exm": "flavor; flavour; taste", "level": "N4"},
  {"char": "写", "meaning": "copy; be photographed", "on": "シャ", "kun": "うつ(す)", "ex": "写真", "exr": "しゃしん", "exm": "photograph; photo; picture", "level": "N4"},
  {"char": "注", "meaning": "pour; irrigate", "on": "チュウ", "kun": "そそ(ぐ)", "ex": "注意", "exr": "ちゅうい", "exm": "attention; notice; heed", "level": "N4"},
  {"char": "悪", "meaning": "bad; vice", "on": "アク", "kun": "わる(い)", "ex": "悪い", "exr": "わるい", "exm": "bad; poor; undesirable", "level": "N4"},
  {"char": "館", "meaning": "building; mansion", "on": "カン", "kun": "やかた", "ex": "大使館", "exr": "たいしかん", "exm": "embassy", "level": "N4"},
  {"char": "屋", "meaning": "roof; house", "on": "オク", "kun": "や", "ex": "部屋", "exr": "へや", "exm": "room; chamber", "level": "N4"},
  {"char": "習", "meaning": "learn", "on": "シュウ", "kun": "なら(う)", "ex": "習う", "exr": "ならう", "exm": "to take lessons in; to be taught; to learn (from a teacher)", "level": "N4"},
  {"char": "駅", "meaning": "station", "on": "エキ", "kun": "—", "ex": "駅", "exr": "えき", "exm": "railway station; train station", "level": "N4"},
  {"char": "洋", "meaning": "ocean; sea", "on": "ヨウ", "kun": "—", "ex": "西洋", "exr": "せいよう", "exm": "the West; the Occident; Western countries", "level": "N4"},
  {"char": "旅", "meaning": "trip; travel", "on": "リョ", "kun": "たび", "ex": "旅行", "exr": "りょこう", "exm": "travel; trip; journey", "level": "N4"},
  {"char": "服", "meaning": "clothing; admit", "on": "フク", "kun": "—", "ex": "服", "exr": "ふく", "exm": "clothes (esp. Western clothes); clothing; dress", "level": "N4"},
  {"char": "飲", "meaning": "drink; smoke", "on": "イン", "kun": "の(む)", "ex": "飲む", "exr": "のむ", "exm": "to drink; to swallow; to take (medicine)", "level": "N4"},
  {"char": "勉", "meaning": "exertion; endeavour", "on": "ベン", "kun": "つと(める)", "ex": "勉強", "exr": "べんきょうする", "exm": "study", "level": "N4"},
  {"char": "漢", "meaning": "sino-; china", "on": "カン", "kun": "—", "ex": "漢字", "exr": "かんじ", "exm": "kanji; Chinese character", "level": "N4"},
  {"char": "不", "meaning": "negative; non-", "on": "フ", "kun": "—", "ex": "不便", "exr": "ふべん", "exm": "inconvenience; inexpediency; unhandiness", "level": "N4"},
  {"char": "以", "meaning": "by means of; because", "on": "イ", "kun": "もっ(て)", "ex": "以下", "exr": "いか", "exm": "not exceeding ...; not more than ...; ... and under", "level": "N4"},
  {"char": "別", "meaning": "separate; branch off", "on": "ベツ", "kun": "わか(れる)", "ex": "別", "exr": "べつ", "exm": "distinction; difference; discrimination", "level": "N4"},
  {"char": "特", "meaning": "special", "on": "トク", "kun": "—", "ex": "特に", "exr": "とくに", "exm": "particularly; especially; in particular", "level": "N4"},
  {"char": "料", "meaning": "fee; materials", "on": "リョウ", "kun": "—", "ex": "料理", "exr": "りょうり", "exm": "cooking; cookery; cuisine", "level": "N4"},
  {"char": "建", "meaning": "build", "on": "ケン", "kun": "た(てる)", "ex": "建物", "exr": "たてもの", "exm": "building", "level": "N4"},
  {"char": "試", "meaning": "test; try", "on": "シ", "kun": "こころ(みる)", "ex": "試合", "exr": "しあい", "exm": "match; game; bout", "level": "N4"},
  {"char": "験", "meaning": "verification; effect", "on": "ケン", "kun": "あかし", "ex": "試験", "exr": "しけん", "exm": "examination; exam; test", "level": "N4"},
  {"char": "英", "meaning": "england; english", "on": "エイ", "kun": "はなぶさ", "ex": "英語", "exr": "えいご", "exm": "English (language)", "level": "N4"},
  {"char": "借", "meaning": "borrow; rent", "on": "シャク", "kun": "か(りる)", "ex": "借りる", "exr": "かりる", "exm": "to borrow", "level": "N4"},
  {"char": "堂", "meaning": "public chamber; hall", "on": "ドウ", "kun": "—", "ex": "食堂", "exr": "しょくどう", "exm": "dining room; dining hall; cafeteria", "level": "N4"},
  {"char": "飯", "meaning": "meal; boiled rice", "on": "ハン", "kun": "めし", "ex": "夕飯", "exr": "ゆうはん", "exm": "evening meal; dinner; supper", "level": "N4"},
  {"char": "質", "meaning": "substance; quality", "on": "シツ", "kun": "たち", "ex": "質問", "exr": "しつもん", "exm": "question; inquiry; enquiry", "level": "N4"},
  {"char": "貸", "meaning": "lend", "on": "タイ", "kun": "か(す)", "ex": "貸す", "exr": "かす", "exm": "to lend; to loan", "level": "N4"},
  {"char": "私", "meaning": "private; i", "on": "シ", "kun": "わたくし", "ex": "私", "exr": "わたくし", "exm": "I; me", "level": "N4"},
  {"char": "映", "meaning": "reflect; reflection", "on": "エイ", "kun": "うつ(る)", "ex": "映画", "exr": "えいが", "exm": "movie; film; motion picture", "level": "N4"},
],
grammar:[
  {"pattern": "〜は〜です", "meaning": "A is B (topic + copula)", "structure": "N は N です", "ex": "わたしは学生です。", "extr": "I am a student.", "level": "N5"},
  {"pattern": "〜は〜ではありません", "meaning": "A is not B", "structure": "N は N ではありません", "ex": "これは本ではありません。", "extr": "This is not a book.", "level": "N5"},
  {"pattern": "〜か（疑問）", "meaning": "question marker", "structure": "sentence + か", "ex": "学生ですか。", "extr": "Are you a student?", "level": "N5"},
  {"pattern": "〜も", "meaning": "also; too", "structure": "N も", "ex": "わたしも行きます。", "extr": "I'll go too.", "level": "N5"},
  {"pattern": "〜の（所有）", "meaning": "'s; of (links nouns)", "structure": "N の N", "ex": "わたしの本です。", "extr": "It is my book.", "level": "N5"},
  {"pattern": "これ・それ・あれ", "meaning": "this / that / that over there", "structure": "demonstrative pronoun", "ex": "これは何ですか。", "extr": "What is this?", "level": "N5"},
  {"pattern": "この・その・あの＋N", "meaning": "this/that + noun", "structure": "この/その/あの + N", "ex": "この本はわたしのです。", "extr": "This book is mine.", "level": "N5"},
  {"pattern": "ここ・そこ・あそこ", "meaning": "here / there / over there", "structure": "place pronoun", "ex": "トイレはあそこです。", "extr": "The toilet is over there.", "level": "N5"},
  {"pattern": "疑問詞（だれ・なに・どこ…）", "meaning": "question words: who/what/where/when", "structure": "question word + か", "ex": "いつ来ますか。", "extr": "When are you coming?", "level": "N5"},
  {"pattern": "Verb ます／ません", "meaning": "polite verb (non-past, aff./neg.)", "structure": "V ます / V ません", "ex": "毎日、日本語を勉強します。", "extr": "I study Japanese every day.", "level": "N5"},
  {"pattern": "Verb ました／ませんでした", "meaning": "polite verb (past, aff./neg.)", "structure": "V ました / V ませんでした", "ex": "昨日、映画を見ました。", "extr": "I watched a movie yesterday.", "level": "N5"},
  {"pattern": "〜を（目的語）", "meaning": "direct object marker", "structure": "N を V", "ex": "ごはんを食べます。", "extr": "I eat rice.", "level": "N5"},
  {"pattern": "〜が（主語）", "meaning": "subject marker", "structure": "N が V", "ex": "ねこがいます。", "extr": "There is a cat.", "level": "N5"},
  {"pattern": "〜に（時間）", "meaning": "at (a point in time)", "structure": "time + に", "ex": "7時に起きます。", "extr": "I get up at 7.", "level": "N5"},
  {"pattern": "〜へ／〜に（方向）", "meaning": "to (direction/destination)", "structure": "place + へ/に + 行く", "ex": "学校へ行きます。", "extr": "I go to school.", "level": "N5"},
  {"pattern": "〜で（場所）", "meaning": "at / in (place of action)", "structure": "place + で + V", "ex": "レストランで食べます。", "extr": "I eat at a restaurant.", "level": "N5"},
  {"pattern": "〜で（手段）", "meaning": "by / with (means)", "structure": "N + で", "ex": "バスで行きます。", "extr": "I go by bus.", "level": "N5"},
  {"pattern": "〜と（一緒に）", "meaning": "with / together with", "structure": "N と", "ex": "友達と行きます。", "extr": "I go with a friend.", "level": "N5"},
  {"pattern": "〜から〜まで", "meaning": "from ~ to ~", "structure": "N から N まで", "ex": "9時から5時まで働きます。", "extr": "I work from 9 to 5.", "level": "N5"},
  {"pattern": "〜があります／います", "meaning": "there is (inanimate / animate)", "structure": "N があります / います", "ex": "机の上に本があります。", "extr": "There is a book on the desk.", "level": "N5"},
  {"pattern": "i-adjective（〜い／〜くない）", "meaning": "i-adjective present aff./neg.", "structure": "adj-い / adj-くない", "ex": "この店は安くないです。", "extr": "This shop is not cheap.", "level": "N5"},
  {"pattern": "i-adjective past（〜かった）", "meaning": "i-adjective past", "structure": "adj-かった / くなかった", "ex": "旅行は楽しかったです。", "extr": "The trip was fun.", "level": "N5"},
  {"pattern": "na-adjective（〜な／〜です）", "meaning": "na-adjective usage", "structure": "adj-な + N / adj です", "ex": "静かな部屋がいいです。", "extr": "I want a quiet room.", "level": "N5"},
  {"pattern": "〜が（逆接）", "meaning": "but; however", "structure": "sentence が sentence", "ex": "高いですが、買います。", "extr": "It's expensive, but I'll buy it.", "level": "N5"},
  {"pattern": "〜から（理由）", "meaning": "because; since", "structure": "plain / です + から", "ex": "寒いですから、コートを着ます。", "extr": "Because it's cold, I wear a coat.", "level": "N5"},
  {"pattern": "〜たいです", "meaning": "want to (do)", "structure": "V(ます-stem) + たい", "ex": "日本で働きたいです。", "extr": "I want to work in Japan.", "level": "N5"},
  {"pattern": "〜がほしい", "meaning": "want (a thing)", "structure": "N がほしい", "ex": "新しい車がほしいです。", "extr": "I want a new car.", "level": "N5"},
  {"pattern": "〜ませんか", "meaning": "won't you? (invitation)", "structure": "V ませんか", "ex": "一緒に行きませんか。", "extr": "Won't you go together?", "level": "N5"},
  {"pattern": "〜ましょう／ましょうか", "meaning": "let's / shall we?", "structure": "V ましょう(か)", "ex": "ちょっと休みましょう。", "extr": "Let's take a break.", "level": "N5"},
  {"pattern": "〜てください", "meaning": "please do", "structure": "V(て) + ください", "ex": "ここに名前を書いてください。", "extr": "Please write your name here.", "level": "N5"},
  {"pattern": "〜ないでください", "meaning": "please don't", "structure": "V(ない) + でください", "ex": "写真を撮らないでください。", "extr": "Please don't take photos.", "level": "N5"},
  {"pattern": "〜ています（進行）", "meaning": "be doing (progressive)", "structure": "V(て) + いる", "ex": "今、本を読んでいます。", "extr": "I am reading a book now.", "level": "N5"},
  {"pattern": "〜ています（状態）", "meaning": "ongoing state (live/marry/know)", "structure": "V(て) + いる", "ex": "大阪に住んでいます。", "extr": "I live in Osaka.", "level": "N5"},
  {"pattern": "〜てから", "meaning": "after doing", "structure": "V(て) + から", "ex": "ごはんを食べてから出かけます。", "extr": "I go out after eating.", "level": "N5"},
  {"pattern": "もう〜ました／まだ〜ていません", "meaning": "already / not yet", "structure": "もう V ました / まだ V ていません", "ex": "もう昼ごはんを食べました。", "extr": "I already ate lunch.", "level": "N5"},
  {"pattern": "〜のほうが〜より", "meaning": "A is more ~ than B", "structure": "A のほうが B より", "ex": "電車のほうがバスより速いです。", "extr": "The train is faster than the bus.", "level": "N5"},
  {"pattern": "〜でいちばん", "meaning": "the most ~ in (a group)", "structure": "N でいちばん + adj", "ex": "クラスでいちばん背が高いです。", "extr": "He is the tallest in the class.", "level": "N5"},
  {"pattern": "〜ね／〜よ", "meaning": "sentence-final particles (agreement / emphasis)", "structure": "sentence + ね/よ", "ex": "いい天気ですね。", "extr": "Nice weather, isn't it?", "level": "N5"},
  {"pattern": "Counters（〜つ・〜まい・〜ほん…）", "meaning": "counting things with counters", "structure": "number + counter", "ex": "りんごを三つ買いました。", "extr": "I bought three apples.", "level": "N5"},
  {"pattern": "〜になる", "meaning": "become", "structure": "N に / adj く + なる", "ex": "寒くなりました。", "extr": "It has gotten cold.", "level": "N5"},
  {"pattern": "〜たり〜たりする", "meaning": "do things like A and B (non-exhaustive)", "structure": "V(past)+り … V(past)+り+する", "ex": "週末は本を読んだり、音楽を聞いたりします。", "extr": "On weekends I do things like reading and listening to music.", "level": "N4"},
  {"pattern": "〜ながら", "meaning": "while doing (two actions at once)", "structure": "V(ます-stem)+ながら", "ex": "音楽を聞きながら勉強します。", "extr": "I study while listening to music.", "level": "N4"},
  {"pattern": "〜たことがある", "meaning": "have done before (experience)", "structure": "V(past)+ことがある", "ex": "日本へ行ったことがあります。", "extr": "I have been to Japan.", "level": "N4"},
  {"pattern": "〜ことができる", "meaning": "be able to / can", "structure": "V(dict.)+ことができる", "ex": "日本語を話すことができます。", "extr": "I can speak Japanese.", "level": "N4"},
  {"pattern": "〜ほうがいい", "meaning": "had better / it is better to", "structure": "V(past)/V(ない)+ほうがいい", "ex": "早く寝たほうがいいです。", "extr": "You'd better sleep early.", "level": "N4"},
  {"pattern": "〜つもり", "meaning": "intend to / plan to", "structure": "V(dict.)/V(ない)+つもり", "ex": "来年、国へ帰るつもりです。", "extr": "I intend to return home next year.", "level": "N4"},
  {"pattern": "〜予定", "meaning": "be scheduled to", "structure": "V(dict.)/Nの+予定", "ex": "来週、試験を受ける予定です。", "extr": "I am scheduled to take the exam next week.", "level": "N4"},
  {"pattern": "〜なければならない", "meaning": "must / have to", "structure": "V(ない-stem)+なければならない", "ex": "薬を飲まなければなりません。", "extr": "I have to take my medicine.", "level": "N4"},
  {"pattern": "〜なくてはいけない", "meaning": "must / have to (spoken)", "structure": "V(ない-stem)+なくてはいけない", "ex": "宿題をしなくてはいけません。", "extr": "I have to do the homework.", "level": "N4"},
  {"pattern": "〜なくてもいい", "meaning": "don't have to", "structure": "V(ない-stem)+なくてもいい", "ex": "明日は来なくてもいいです。", "extr": "You don't have to come tomorrow.", "level": "N4"},
  {"pattern": "〜てもいい", "meaning": "may / it is OK to", "structure": "V(て)+もいい", "ex": "ここで写真を撮ってもいいです。", "extr": "You may take photos here.", "level": "N4"},
  {"pattern": "〜てはいけない", "meaning": "must not", "structure": "V(て)+はいけない", "ex": "ここでたばこを吸ってはいけません。", "extr": "You must not smoke here.", "level": "N4"},
  {"pattern": "〜ておく", "meaning": "do in advance / leave as is", "structure": "V(て)+おく", "ex": "旅行の前に切符を買っておきます。", "extr": "I'll buy the tickets in advance.", "level": "N4"},
  {"pattern": "〜てしまう", "meaning": "finish completely / do by mistake (regret)", "structure": "V(て)+しまう", "ex": "財布を忘れてしまいました。", "extr": "I (regrettably) forgot my wallet.", "level": "N4"},
  {"pattern": "〜てみる", "meaning": "try doing (and see)", "structure": "V(て)+みる", "ex": "この服を着てみます。", "extr": "I'll try on these clothes.", "level": "N4"},
  {"pattern": "〜ている ところ", "meaning": "in the middle of doing", "structure": "V(ている)+ところ", "ex": "今、食べているところです。", "extr": "I am in the middle of eating now.", "level": "N4"},
  {"pattern": "〜たばかり", "meaning": "just did (moments ago)", "structure": "V(past)+ばかり", "ex": "さっき着いたばかりです。", "extr": "I just arrived a moment ago.", "level": "N4"},
  {"pattern": "〜そうだ（様態）", "meaning": "looks like / seems (from appearance)", "structure": "V(ます-stem)/adj-stem+そう", "ex": "雨が降りそうです。", "extr": "It looks like it will rain.", "level": "N4"},
  {"pattern": "〜そうだ（伝聞）", "meaning": "I hear that / they say (hearsay)", "structure": "plain form+そうだ", "ex": "田中さんは来ないそうです。", "extr": "I hear that Tanaka isn't coming.", "level": "N4"},
  {"pattern": "〜ようだ", "meaning": "seems like (inference from evidence)", "structure": "plain form+ようだ", "ex": "彼は忙しいようです。", "extr": "He seems to be busy.", "level": "N4"},
  {"pattern": "〜らしい", "meaning": "apparently / seems (hearsay)", "structure": "plain form+らしい", "ex": "あの店は安いらしいです。", "extr": "Apparently that shop is cheap.", "level": "N4"},
  {"pattern": "〜みたい", "meaning": "looks like / resembles (casual)", "structure": "N/plain form+みたい", "ex": "子供みたいですね。", "extr": "You're like a child.", "level": "N4"},
  {"pattern": "〜かもしれない", "meaning": "might / maybe", "structure": "plain form+かもしれない", "ex": "明日は雪が降るかもしれません。", "extr": "It might snow tomorrow.", "level": "N4"},
  {"pattern": "〜はず", "meaning": "should be / is expected to", "structure": "plain form+はず", "ex": "彼はもう着いたはずです。", "extr": "He should have arrived already.", "level": "N4"},
  {"pattern": "〜はずがない", "meaning": "cannot possibly be", "structure": "plain form+はずがない", "ex": "彼が来ないはずがない。", "extr": "There's no way he won't come.", "level": "N4"},
  {"pattern": "〜でしょう / だろう", "meaning": "probably / I suppose", "structure": "plain form+でしょう", "ex": "明日は晴れるでしょう。", "extr": "It will probably be sunny tomorrow.", "level": "N4"},
  {"pattern": "〜と思う", "meaning": "I think that", "structure": "plain form+と思う", "ex": "彼は正しいと思います。", "extr": "I think he is right.", "level": "N4"},
  {"pattern": "〜と言う", "meaning": "say that / named", "structure": "plain form / N+という", "ex": "「みどり」という店です。", "extr": "It's a shop called \"Midori\".", "level": "N4"},
  {"pattern": "Potential form", "meaning": "can do / be able to", "structure": "V→V(れる/られる)", "ex": "刺身が食べられます。", "extr": "I can eat sashimi.", "level": "N4"},
  {"pattern": "Volitional 〜(よ)う", "meaning": "let's / I'll (intention)", "structure": "V→V(volitional)", "ex": "一緒に行こう。", "extr": "Let's go together.", "level": "N4"},
  {"pattern": "〜(よ)うと思う", "meaning": "I am thinking of doing", "structure": "V(volitional)+と思う", "ex": "日本で働こうと思います。", "extr": "I'm thinking of working in Japan.", "level": "N4"},
  {"pattern": "〜てあげる", "meaning": "do (a favour) for someone", "structure": "V(て)+あげる", "ex": "友達に本を貸してあげました。", "extr": "I lent my friend a book.", "level": "N4"},
  {"pattern": "〜てくれる", "meaning": "someone does (a favour) for me", "structure": "V(て)+くれる", "ex": "友達が手伝ってくれました。", "extr": "My friend helped me.", "level": "N4"},
  {"pattern": "〜てもらう", "meaning": "have someone do (for me)", "structure": "V(て)+もらう", "ex": "先生に説明してもらいました。", "extr": "I had the teacher explain it to me.", "level": "N4"},
  {"pattern": "あげる / くれる / もらう", "meaning": "give / give (to me) / receive", "structure": "N+を+あげる/くれる/もらう", "ex": "父が時計をくれました。", "extr": "My father gave me a watch.", "level": "N4"},
  {"pattern": "〜たら", "meaning": "if / when (once A, then B)", "structure": "V(past)+ら", "ex": "時間があったら、映画を見ます。", "extr": "If I have time, I'll watch a movie.", "level": "N4"},
  {"pattern": "〜ば", "meaning": "if (conditional)", "structure": "V→V(ば form)", "ex": "安ければ買います。", "extr": "If it's cheap, I'll buy it.", "level": "N4"},
  {"pattern": "〜と（条件）", "meaning": "whenever / if (natural result)", "structure": "V(dict.)+と", "ex": "このボタンを押すと、開きます。", "extr": "If you press this button, it opens.", "level": "N4"},
  {"pattern": "〜なら", "meaning": "if (given that / as for)", "structure": "N/plain form+なら", "ex": "日本へ行くなら、京都がいいです。", "extr": "If you're going to Japan, Kyoto is good.", "level": "N4"},
  {"pattern": "〜ても", "meaning": "even if", "structure": "V(て)+も", "ex": "雨が降っても行きます。", "extr": "Even if it rains, I will go.", "level": "N4"},
  {"pattern": "Passive form", "meaning": "be done to (happens to me)", "structure": "V→V(れる/られる)", "ex": "先生に褒められました。", "extr": "I was praised by the teacher.", "level": "N4"},
  {"pattern": "Causative form", "meaning": "make / let someone do", "structure": "V→V(せる/させる)", "ex": "子供に野菜を食べさせます。", "extr": "I make my child eat vegetables.", "level": "N4"},
  {"pattern": "Causative-passive", "meaning": "be made to do", "structure": "V→V(させられる)", "ex": "たくさん飲まされました。", "extr": "I was made to drink a lot.", "level": "N4"},
  {"pattern": "〜すぎる", "meaning": "too much / excessively", "structure": "V(ます-stem)/adj-stem+すぎる", "ex": "食べすぎました。", "extr": "I ate too much.", "level": "N4"},
  {"pattern": "〜やすい / 〜にくい", "meaning": "easy / hard to do", "structure": "V(ます-stem)+やすい/にくい", "ex": "この本は読みやすいです。", "extr": "This book is easy to read.", "level": "N4"},
  {"pattern": "〜方（かた）", "meaning": "way of doing", "structure": "V(ます-stem)+方", "ex": "使い方が分かりません。", "extr": "I don't know how to use it.", "level": "N4"},
  {"pattern": "〜ように", "meaning": "so that / in such a way that", "structure": "V(dict.)/V(ない)+ように", "ex": "忘れないようにメモします。", "extr": "I make a note so I won't forget.", "level": "N4"},
  {"pattern": "〜ようになる", "meaning": "come to / reach the point where", "structure": "V(dict.)+ようになる", "ex": "日本語が話せるようになりました。", "extr": "I have become able to speak Japanese.", "level": "N4"},
  {"pattern": "〜ようにする", "meaning": "try to / make an effort to", "structure": "V(dict.)/V(ない)+ようにする", "ex": "毎日運動するようにしています。", "extr": "I try to exercise every day.", "level": "N4"},
  {"pattern": "〜ことにする", "meaning": "decide to", "structure": "V(dict.)/V(ない)+ことにする", "ex": "たばこをやめることにしました。", "extr": "I decided to quit smoking.", "level": "N4"},
  {"pattern": "〜ことになる", "meaning": "it has been decided that", "structure": "V(dict.)+ことになる", "ex": "来月、出張することになりました。", "extr": "It's been decided I'll take a business trip next month.", "level": "N4"},
  {"pattern": "〜あいだに", "meaning": "while / during", "structure": "Nの/V(ている)+あいだに", "ex": "昼休みのあいだに買い物をします。", "extr": "I shop during the lunch break.", "level": "N4"},
  {"pattern": "〜まえに", "meaning": "before doing", "structure": "V(dict.)/Nの+まえに", "ex": "寝るまえに歯を磨きます。", "extr": "I brush my teeth before sleeping.", "level": "N4"},
  {"pattern": "〜あとで", "meaning": "after doing", "structure": "V(past)/Nの+あとで", "ex": "食事のあとで散歩します。", "extr": "I take a walk after meals.", "level": "N4"},
  {"pattern": "〜とき", "meaning": "when / at the time of", "structure": "plain form/Nの+とき", "ex": "子供のとき、よく泳ぎました。", "extr": "When I was a child, I often swam.", "level": "N4"},
  {"pattern": "〜ため(に)", "meaning": "for the purpose of / because", "structure": "V(dict.)/Nの+ため(に)", "ex": "健康のために運動します。", "extr": "I exercise for my health.", "level": "N4"},
  {"pattern": "〜し、〜し", "meaning": "and (listing reasons)", "structure": "plain form+し", "ex": "安いし、おいしいし、この店が好きです。", "extr": "It's cheap and tasty, so I like this shop.", "level": "N4"},
  {"pattern": "〜のに", "meaning": "even though / although", "structure": "plain form+のに", "ex": "薬を飲んだのに、治りません。", "extr": "Even though I took medicine, I'm not getting better.", "level": "N4"},
  {"pattern": "〜ので", "meaning": "because / since (polite reason)", "structure": "plain form+ので", "ex": "雨なので、行きません。", "extr": "Because it's raining, I won't go.", "level": "N4"},
  {"pattern": "〜のだ / んです", "meaning": "explanatory (the fact is…)", "structure": "plain form+んです", "ex": "頭が痛いんです。", "extr": "The thing is, I have a headache.", "level": "N4"},
  {"pattern": "〜かどうか", "meaning": "whether or not", "structure": "plain form+かどうか", "ex": "来るかどうか分かりません。", "extr": "I don't know whether he'll come.", "level": "N4"},
  {"pattern": "疑問詞＋か", "meaning": "embedded question (what/where/…)", "structure": "question word+…か", "ex": "どこに住んでいるか知りません。", "extr": "I don't know where he lives.", "level": "N4"},
  {"pattern": "〜てある", "meaning": "has been done (state left on purpose)", "structure": "V(て)+ある", "ex": "ドアが開けてあります。", "extr": "The door has been (left) opened.", "level": "N4"},
  {"pattern": "〜ていく / 〜てくる", "meaning": "go on doing / come to do (change over time)", "structure": "V(て)+いく/くる", "ex": "だんだん寒くなってきました。", "extr": "It's gradually gotten cold.", "level": "N4"},
  {"pattern": "〜がる", "meaning": "shows another's feeling (wants/…)", "structure": "adj-stem+がる", "ex": "子供が犬を怖がっています。", "extr": "The child is afraid of the dog.", "level": "N4"},
  {"pattern": "〜たがる", "meaning": "someone (else) wants to do", "structure": "V(ます-stem)+たがる", "ex": "弟は行きたがっています。", "extr": "My little brother wants to go.", "level": "N4"},
  {"pattern": "〜という／〜ということ", "meaning": "nominalise / \"the fact that\"", "structure": "plain form+ということ", "ex": "日本語は難しいということが分かりました。", "extr": "I realised that Japanese is difficult.", "level": "N4"},
  {"pattern": "お〜になる（尊敬）", "meaning": "respectful (about others)", "structure": "お+V(ます-stem)+になる", "ex": "先生はもうお帰りになりました。", "extr": "The teacher has already gone home.", "level": "N4"},
  {"pattern": "お〜する（謙譲）", "meaning": "humble (about oneself)", "structure": "お+V(ます-stem)+する", "ex": "私がお持ちします。", "extr": "I'll carry it (humble).", "level": "N4"},
  {"pattern": "いらっしゃる", "meaning": "honorific for be/come/go", "structure": "special respectful verb", "ex": "先生がいらっしゃいます。", "extr": "The teacher is here / is coming.", "level": "N4"},
  {"pattern": "〜ていただけませんか", "meaning": "could you please…? (very polite)", "structure": "V(て)+いただけませんか", "ex": "手伝っていただけませんか。", "extr": "Could you please help me?", "level": "N4"},
  {"pattern": "〜なさい", "meaning": "do…! (soft command)", "structure": "V(ます-stem)+なさい", "ex": "早く寝なさい。", "extr": "Go to sleep (now).", "level": "N4"},
  {"pattern": "〜な（禁止）", "meaning": "don't…! (prohibition)", "structure": "V(dict.)+な", "ex": "ここに入るな。", "extr": "Don't enter here.", "level": "N4"},
  {"pattern": "〜ば〜ほど", "meaning": "the more…, the more…", "structure": "V(ば)+V(dict.)+ほど", "ex": "見れば見るほど好きになります。", "extr": "The more I look, the more I like it.", "level": "N4"},
  {"pattern": "〜こそ", "meaning": "precisely / it is exactly…", "structure": "N+こそ", "ex": "今年こそ合格します。", "extr": "This year for sure, I'll pass.", "level": "N4"},
  {"pattern": "〜として", "meaning": "as / in the role of", "structure": "N+として", "ex": "留学生として日本へ来ました。", "extr": "I came to Japan as an exchange student.", "level": "N4"},
  {"pattern": "〜について", "meaning": "about / concerning", "structure": "N+について", "ex": "日本の文化について研究します。", "extr": "I research about Japanese culture.", "level": "N4"},
  {"pattern": "〜によって", "meaning": "depending on / by means of", "structure": "N+によって", "ex": "人によって考え方が違います。", "extr": "Ways of thinking differ from person to person.", "level": "N4"},
  {"pattern": "〜おわる / 〜はじめる / 〜つづける", "meaning": "finish / start / keep doing", "structure": "V(ます-stem)+おわる/はじめる/つづける", "ex": "読み終わりました。", "extr": "I finished reading.", "level": "N4"},
  {"pattern": "〜さ", "meaning": "-ness (adjective → noun)", "structure": "adj-stem+さ", "ex": "この山の高さは3000mです。", "extr": "This mountain's height is 3000m.", "level": "N4"},
],
vocab:[
  {"word": "あ", "reading": "あ", "meaning": "ah; oh (surprise, recognition)", "pos": "interjection", "level": "N4"},
  {"word": "あの", "reading": "あの", "meaning": "that; those; the", "pos": "", "level": "N5"},
  {"word": "ある", "reading": "ある", "meaning": "a certain ...; some ...", "pos": "", "level": "N5"},
  {"word": "あれ", "reading": "あれ", "meaning": "let there be ...; may it be ...", "pos": "expression", "level": "N5"},
  {"word": "いい", "reading": "いい", "meaning": "good; excellent; fine", "pos": "i-adjective", "level": "N5"},
  {"word": "いい", "reading": "よい", "meaning": "good; excellent; fine", "pos": "i-adjective", "level": "N5"},
  {"word": "よい", "reading": "いい", "meaning": "affectionately attached; reluctant to part", "pos": "adverb", "level": "N5"},
  {"word": "よい", "reading": "よい", "meaning": "implied meaning", "pos": "noun", "level": "N5"},
  {"word": "いす", "reading": "いす", "meaning": "chair; seat; stool", "pos": "noun", "level": "N5"},
  {"word": "いつ", "reading": "いつ", "meaning": "when; at what time; how soon", "pos": "pronoun", "level": "N5"},
  {"word": "ええ", "reading": "ええ", "meaning": "yes; that is correct; right", "pos": "interjection", "level": "N5"},
  {"word": "かぎ", "reading": "かぎ", "meaning": "member of the lower house", "pos": "noun", "level": "N5"},
  {"word": "キロ", "reading": "キロ", "meaning": "kilo-; 1000; French", "pos": "prefix", "level": "N5"},
  {"word": "キロ", "reading": "キログラム", "meaning": "kilo-; 1000; French", "pos": "prefix", "level": "N5"},
  {"word": "キロ", "reading": "キロメートル", "meaning": "kilo-; 1000; French", "pos": "prefix", "level": "N5"},
  {"word": "ここ", "reading": "ここ", "meaning": "here; this place", "pos": "pronoun", "level": "N5"},
  {"word": "この", "reading": "この", "meaning": "this; something or someone close to the speaker (including the speaker), or ideas expressed by the speaker", "pos": "", "level": "N5"},
  {"word": "これ", "reading": "これ", "meaning": "hey; oi; come on", "pos": "interjection", "level": "N5"},
  {"word": "さあ", "reading": "さあ", "meaning": "come (on); come now; come along", "pos": "interjection", "level": "N5"},
  {"word": "じゃ", "reading": "じゃ", "meaning": "be; is; western Japanese; also freq. used in animation and foreign-language dubbing to indicate a person is old", "pos": "", "level": "N5"},
  {"word": "じゃ", "reading": "じゃあ", "meaning": "be; is; western Japanese; also freq. used in animation and foreign-language dubbing to indicate a person is old", "pos": "", "level": "N5"},
  {"word": "する", "reading": "する", "meaning": "to do; to carry out; to perform", "pos": "する-verb", "level": "N5"},
  {"word": "ゼロ", "reading": "ゼロ", "meaning": "zero; 0; nought", "pos": "noun", "level": "N5"},
  {"word": "そこ", "reading": "そこ", "meaning": "there (place relatively near listener)", "pos": "pronoun", "level": "N5"},
  {"word": "その", "reading": "その", "meaning": "that; the; something or someone distant from the speaker, close to the listener; actions of the listener, or ideas expressed or understood by the listener", "pos": "", "level": "N5"},
  {"word": "そば", "reading": "そば", "meaning": "near; close; beside", "pos": "noun", "level": "N5"},
  {"word": "それ", "reading": "それ", "meaning": "there!; look!; used to call someone's attention to something", "pos": "interjection", "level": "N5"},
  {"word": "たて", "reading": "たて", "meaning": "shield; buckler; escutcheon", "pos": "noun", "level": "N5"},
  {"word": "では", "reading": "では", "meaning": "then; well; so", "pos": "conjunction", "level": "N5"},
  {"word": "でも", "reading": "でも", "meaning": "but; however; though", "pos": "conjunction", "level": "N5"},
  {"word": "ドア", "reading": "ドア", "meaning": "door", "pos": "noun", "level": "N5"},
  {"word": "どう", "reading": "どう", "meaning": "how; in what way; how about", "pos": "adverb", "level": "N5"},
  {"word": "どこ", "reading": "どこ", "meaning": "where; what place", "pos": "pronoun", "level": "N5"},
  {"word": "どの", "reading": "どの", "meaning": "which; what (way)", "pos": "", "level": "N5"},
  {"word": "どれ", "reading": "どれ", "meaning": "which (of three or more)", "pos": "pronoun", "level": "N5"},
  {"word": "なぜ", "reading": "なぜ", "meaning": "why; how; for what reason", "pos": "adverb", "level": "N5"},
  {"word": "など", "reading": "など", "meaning": "et cetera; etc.; and the like", "pos": "particle", "level": "N5"},
  {"word": "なる", "reading": "なる", "meaning": "that is in", "pos": "suffix", "level": "N5"},
  {"word": "はい", "reading": "はい", "meaning": "yes; that is correct", "pos": "interjection", "level": "N5"},
  {"word": "はく", "reading": "はく", "meaning": "count; earl", "pos": "noun", "level": "N5"},
  {"word": "はし", "reading": "はし", "meaning": "bridge", "pos": "noun", "level": "N5"},
  {"word": "バス", "reading": "バス", "meaning": "bass; German:; Bass", "pos": "noun", "level": "N5"},
  {"word": "パン", "reading": "パン", "meaning": "pan; frying pan", "pos": "noun", "level": "N5"},
  {"word": "ふろ", "reading": "ふろ", "meaning": "bath; bathing; bathtub", "pos": "noun", "level": "N5"},
  {"word": "ペン", "reading": "ペン", "meaning": "pen", "pos": "noun", "level": "N5"},
  {"word": "ほか", "reading": "ほか", "meaning": "another place; some other place; somewhere else", "pos": "noun", "level": "N5"},
  {"word": "また", "reading": "また", "meaning": "groin; thigh; crotch", "pos": "noun", "level": "N5"},
  {"word": "まだ", "reading": "まだ", "meaning": "still; as yet; only", "pos": "adverb", "level": "N5"},
  {"word": "もう", "reading": "もう", "meaning": "already; yet; by now", "pos": "adverb", "level": "N5"},
  {"word": "やる", "reading": "やる", "meaning": "to do; to undertake; to perform", "pos": "verb (u)", "level": "N5"},
  {"word": "よく", "reading": "よく", "meaning": "greed; craving; desire", "pos": "noun", "level": "N5"},
  {"word": "より", "reading": "より", "meaning": "than", "pos": "particle", "level": "N5"},
  {"word": "より", "reading": "ほう", "meaning": "than", "pos": "particle", "level": "N5"},
  {"word": "ほう", "reading": "より", "meaning": "oh; ho; exclamation of surprise, admiration, etc.", "pos": "interjection", "level": "N5"},
  {"word": "ほう", "reading": "ほう", "meaning": "oh; ho; exclamation of surprise, admiration, etc.", "pos": "interjection", "level": "N5"},
  {"word": "ああ", "reading": "ああ", "meaning": "ah!; oh!; alas!", "pos": "interjection", "level": "N4"},
  {"word": "うそ", "reading": "うそ", "meaning": "Eurasian bullfinch (Pyrrhula pyrrhula); Japanese bullfinch", "pos": "noun", "level": "N4"},
  {"word": "うち", "reading": "うち", "meaning": "inside; within", "pos": "noun", "level": "N4"},
  {"word": "うん", "reading": "うん", "meaning": "yes; yeah; uh huh", "pos": "interjection", "level": "N4"},
  {"word": "ガス", "reading": "ガス", "meaning": "gas (as a fuel); Dutch; English", "pos": "noun", "level": "N4"},
]
};
